# main settings
title:            METRO/599 Grants
description:      a jekyll theme for minimal exhibitions
url:              '' # the url should stay empty
baseurl:          '/grants' # the baseurl of your site must be defined but can be an empty ''

# build settings
permalink:        pretty
exclude:          [Gemfile*, Rakefile, vendor, spec, README.md]

# wax collection settings
collections:
  grants:
    output: true
    source: grants.csv
    layout: grants_item
    lunr_index:
      content: false
      fields: [pid,grant_year_type,institution_name,collection_name,description,title]
    iiif:
      meta:
        label: title

# menu settings
menu:
  - label: Gallery
    link: /gallery/

# search tests. run with $ bundle exec rspec
quoll:
  main:
    page: '/' # the path of the page you want to test
    terms:  # the search terms you expect to yield results
      - iran
      - map
      - manuscript

# javascript dependencies
js:
  jquery:
    version: 3.2.1
    cdn: //code.jquery.com/jquery-3.2.1.min.js
  popper:
    version: 1.12.9
    cdn: //cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js
  bootstrap:
    version: 4.0.0
    cdn: //maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js
  leaflet:
    version: 1.3.1
    cdn: //unpkg.com/leaflet@1.3.1/dist/leaflet.js
  leaflet-iiif:
    version: 2.0.1
    cdn: //cdn.jsdelivr.net/npm/leaflet-iiif@2.0.1/leaflet-iiif.min.js

# cors headers for iiif use
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
